-- ============================================================
-- بيانات تجريبية أولية (Seed data) - نفس بيانات العرض التوضيحي
-- نفّذ هذا الملف بعد schema.sql (مرة وحدة فقط)
-- ============================================================

insert into public.categories (id, name) values
  ('cat-pain', '{"ar":"مسكنات الألم","fr":"Antidouleurs","en":"Painkillers"}'::jsonb),
  ('cat-antibio', '{"ar":"مضادات حيوية","fr":"Antibiotiques","en":"Antibiotics"}'::jsonb),
  ('cat-vitamin', '{"ar":"فيتامينات ومكملات","fr":"Vitamines & compléments","en":"Vitamins & supplements"}'::jsonb),
  ('cat-digestive', '{"ar":"الجهاز الهضمي","fr":"Digestif","en":"Digestive"}'::jsonb),
  ('cat-respiratory', '{"ar":"الجهاز التنفسي","fr":"Respiratoire","en":"Respiratory"}'::jsonb)
on conflict (id) do nothing;

insert into public.guide_categories (id, icon, name) values
  ('gc-diabetes', '🩸', '{"ar":"السكري","fr":"Diabète","en":"Diabetes"}'::jsonb),
  ('gc-hypertension', '❤️', '{"ar":"ارتفاع ضغط الدم","fr":"Hypertension","en":"Hypertension"}'::jsonb),
  ('gc-cholesterol', '🫀', '{"ar":"الكوليسترول","fr":"Cholestérol","en":"Cholesterol"}'::jsonb),
  ('gc-weight', '⚖️', '{"ar":"التحكم في الوزن","fr":"Gestion du poids","en":"Weight control"}'::jsonb)
on conflict (id) do nothing;

insert into public.medicines (name, "categoryId", "activeIngredient", concentration, form, price, availability, image, info) values
  ('Paracetamol 500mg', 'cat-pain', '{"ar":"باراسيتامول","fr":"Paracétamol","en":"Paracetamol"}'::jsonb, '500mg', '{"ar":"قرص","fr":"Comprimé","en":"Tablet"}'::jsonb, 12, 'available', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', '{"general":{"ar":"مسكن للألم وخافض للحرارة يُستخدم على نطاق واسع.","fr":"Antalgique et antipyrétique largement utilisé.","en":"A widely used pain reliever and fever reducer."},"usage":{"ar":"تخفيف الصداع، آلام العضلات، الحمى.","fr":"Soulage les maux de tête, douleurs musculaires, fièvre.","en":"Relieves headaches, muscle pain, fever."},"howToUse":{"ar":"قرص واحد كل 6 إلى 8 ساعات حسب الحاجة، دون تجاوز الجرعة الموصى بها.","fr":"Un comprimé toutes les 6 à 8 heures si besoin, sans dépasser la dose recommandée.","en":"One tablet every 6–8 hours as needed, without exceeding the recommended dose."},"warnings":{"ar":"تجنب تجاوز الجرعة اليومية القصوى. استشر الصيدلي في حال وجود أمراض كبدية.","fr":"Ne pas dépasser la dose quotidienne maximale. Consultez en cas de maladie hépatique.","en":"Do not exceed the maximum daily dose. Consult in case of liver conditions."},"contraindications":{"ar":"الحساسية تجاه الباراسيتامول.","fr":"Allergie au paracétamol.","en":"Allergy to paracetamol."},"sideEffects":{"ar":"نادرة عند الاستخدام الصحيح، قد تشمل اضطرابات هضمية بسيطة.","fr":"Rares à dose correcte, parfois troubles digestifs légers.","en":"Rare at correct doses, may include mild digestive upset."}}'::jsonb),
  ('Paracetamol 1g', 'cat-pain', '{"ar":"باراسيتامول","fr":"Paracétamol","en":"Paracetamol"}'::jsonb, '1g', '{"ar":"قرص فوار","fr":"Comprimé effervescent","en":"Effervescent tablet"}'::jsonb, 18, 'available', 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', '{"general":{"ar":"صيغة مقواة لتخفيف الآلام المتوسطة إلى الشديدة.","fr":"Formule renforcée pour douleurs modérées à sévères.","en":"Stronger formula for moderate to severe pain."},"usage":{"ar":"آلام الظهر، الصداع النصفي، الحمى المرتفعة.","fr":"Douleurs dorsales, migraines, fièvre élevée.","en":"Back pain, migraines, high fever."},"howToUse":{"ar":"قرص فوار واحد مذاب في كوب ماء، حتى 3 مرات يوميًا.","fr":"Un comprimé effervescent dans un verre d''eau, jusqu''à 3 fois par jour.","en":"One effervescent tablet dissolved in water, up to 3 times daily."},"warnings":{"ar":"غير موصى به للأطفال دون 12 سنة إلا بإشراف طبي.","fr":"Non recommandé aux enfants de moins de 12 ans sans avis médical.","en":"Not recommended for children under 12 without medical advice."},"contraindications":{"ar":"قصور كبدي حاد.","fr":"Insuffisance hépatique sévère.","en":"Severe liver failure."},"sideEffects":{"ar":"نادرة، قد تشمل غثيان خفيف.","fr":"Rares, nausées légères possibles.","en":"Rare, mild nausea possible."}}'::jsonb),
  ('Ibuprofen 400mg', 'cat-pain', '{"ar":"إيبوبروفين","fr":"Ibuprofène","en":"Ibuprofen"}'::jsonb, '400mg', '{"ar":"قرص","fr":"Comprimé","en":"Tablet"}'::jsonb, 22, 'limited', 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', '{"general":{"ar":"مضاد التهاب غير ستيرويدي يخفف الألم والالتهاب.","fr":"Anti-inflammatoire non stéroïdien qui réduit douleur et inflammation.","en":"A non-steroidal anti-inflammatory that reduces pain and inflammation."},"usage":{"ar":"آلام المفاصل، الدورة الشهرية، الالتهابات الخفيفة.","fr":"Douleurs articulaires, règles douloureuses, inflammations légères.","en":"Joint pain, menstrual pain, mild inflammation."},"howToUse":{"ar":"قرص واحد بعد الأكل، 2 إلى 3 مرات يوميًا.","fr":"Un comprimé après repas, 2 à 3 fois par jour.","en":"One tablet after meals, 2–3 times daily."},"warnings":{"ar":"يُفضل تناوله بعد الأكل لتجنب اضطرابات المعدة.","fr":"À prendre après les repas pour éviter les troubles gastriques.","en":"Best taken after meals to avoid stomach upset."},"contraindications":{"ar":"قرحة المعدة النشطة، الحمل في الثلث الأخير.","fr":"Ulcère gastrique actif, dernier trimestre de grossesse.","en":"Active stomach ulcer, third trimester of pregnancy."},"sideEffects":{"ar":"حرقة معدة، دوخة خفيفة.","fr":"Brûlures d''estomac, légers vertiges.","en":"Heartburn, mild dizziness."}}'::jsonb),
  ('Amoxicilline 500mg', 'cat-antibio', '{"ar":"أموكسيسيلين","fr":"Amoxicilline","en":"Amoxicillin"}'::jsonb, '500mg', '{"ar":"كبسولة","fr":"Gélule","en":"Capsule"}'::jsonb, 35, 'available', 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', '{"general":{"ar":"مضاد حيوي واسع الطيف من عائلة البنسلين.","fr":"Antibiotique à large spectre de la famille des pénicillines.","en":"A broad-spectrum antibiotic from the penicillin family."},"usage":{"ar":"علاج التهابات بكتيرية متنوعة حسب وصفة الطبيب.","fr":"Traitement de diverses infections bactériennes sur ordonnance.","en":"Treats various bacterial infections as prescribed."},"howToUse":{"ar":"يُصرف بوصفة طبية فقط، حسب تعليمات الطبيب.","fr":"Délivré uniquement sur ordonnance, selon prescription médicale.","en":"Dispensed by prescription only, as directed by the doctor."},"warnings":{"ar":"يجب إكمال مدة العلاج كاملة حسب وصفة الطبيب.","fr":"Le traitement doit être terminé intégralement selon la prescription.","en":"The full course must be completed as prescribed."},"contraindications":{"ar":"الحساسية تجاه البنسلين.","fr":"Allergie à la pénicilline.","en":"Penicillin allergy."},"sideEffects":{"ar":"اضطرابات هضمية، طفح جلدي نادر.","fr":"Troubles digestifs, éruption cutanée rare.","en":"Digestive upset, rare skin rash."}}'::jsonb),
  ('Vitamine C 1000mg', 'cat-vitamin', '{"ar":"فيتامين سي","fr":"Vitamine C","en":"Vitamin C"}'::jsonb, '1000mg', '{"ar":"قرص فوار","fr":"Comprimé effervescent","en":"Effervescent tablet"}'::jsonb, 45, 'available', 'https://images.unsplash.com/photo-1616671276441-2f2c277b8bf6?w=600&q=80', '{"general":{"ar":"مكمل غذائي يدعم جهاز المناعة.","fr":"Complément alimentaire qui soutient le système immunitaire.","en":"A dietary supplement that supports the immune system."},"usage":{"ar":"تقوية المناعة، فترات التعب والإرهاق.","fr":"Renforcement immunitaire, périodes de fatigue.","en":"Immune support, periods of fatigue."},"howToUse":{"ar":"قرص فوار واحد يوميًا مذاب في الماء.","fr":"Un comprimé effervescent par jour dans de l''eau.","en":"One effervescent tablet daily dissolved in water."},"warnings":{"ar":"الإفراط في الجرعة قد يسبب اضطرابات هضمية.","fr":"Un surdosage peut causer des troubles digestifs.","en":"Overdosing may cause digestive discomfort."},"contraindications":{"ar":"حصى الكلى المتكررة.","fr":"Calculs rénaux récurrents.","en":"Recurrent kidney stones."},"sideEffects":{"ar":"نادرة عند الجرعات المعتادة.","fr":"Rares aux doses habituelles.","en":"Rare at usual doses."}}'::jsonb),
  ('Vitamine D3', 'cat-vitamin', '{"ar":"فيتامين د3","fr":"Vitamine D3","en":"Vitamin D3"}'::jsonb, '1000 UI', '{"ar":"قطرات","fr":"Gouttes","en":"Drops"}'::jsonb, 55, 'available', 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', '{"general":{"ar":"يدعم صحة العظام وامتصاص الكالسيوم.","fr":"Soutient la santé osseuse et l''absorption du calcium.","en":"Supports bone health and calcium absorption."},"usage":{"ar":"نقص فيتامين د، دعم صحة العظام.","fr":"Carence en vitamine D, soutien osseux.","en":"Vitamin D deficiency, bone support."},"howToUse":{"ar":"حسب إرشادات الطبيب أو الصيدلي.","fr":"Selon les indications du médecin ou du pharmacien.","en":"As advised by the doctor or pharmacist."},"warnings":{"ar":"تجنب الجرعات الزائدة على المدى الطويل.","fr":"Éviter le surdosage prolongé.","en":"Avoid prolonged overdosing."},"contraindications":{"ar":"فرط كالسيوم الدم.","fr":"Hypercalcémie.","en":"Hypercalcemia."},"sideEffects":{"ar":"نادرة عند الاستخدام السليم.","fr":"Rares à usage correct.","en":"Rare with proper use."}}'::jsonb),
  ('Smecta', 'cat-digestive', '{"ar":"ديوسمكتيت","fr":"Diosmectite","en":"Diosmectite"}'::jsonb, '3g', '{"ar":"شراب","fr":"Sirop","en":"Syrup"}'::jsonb, 28, 'available', 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&q=80', '{"general":{"ar":"يستخدم لعلاج الإسهال الحاد والمزمن.","fr":"Utilisé dans le traitement de la diarrhée aiguë et chronique.","en":"Used to treat acute and chronic diarrhea."},"usage":{"ar":"الإسهال، اضطرابات القولون.","fr":"Diarrhée, troubles intestinaux.","en":"Diarrhea, bowel discomfort."},"howToUse":{"ar":"كيس واحد مذاب في الماء، 2 إلى 3 مرات يوميًا.","fr":"Un sachet dans de l''eau, 2 à 3 fois par jour.","en":"One sachet dissolved in water, 2–3 times daily."},"warnings":{"ar":"يُنصح بمباعدته عن أدوية أخرى بساعتين.","fr":"Espacer de 2 heures avec d''autres médicaments.","en":"Space at least 2 hours apart from other medications."},"contraindications":{"ar":"لا يوجد موانع رئيسية معروفة.","fr":"Aucune contre-indication majeure connue.","en":"No major known contraindications."},"sideEffects":{"ar":"إمساك خفيف محتمل.","fr":"Constipation légère possible.","en":"Mild constipation possible."}}'::jsonb),
  ('Gaviscon', 'cat-digestive', '{"ar":"ألجينات الصوديوم","fr":"Alginate de sodium","en":"Sodium alginate"}'::jsonb, '10ml', '{"ar":"شراب","fr":"Sirop","en":"Syrup"}'::jsonb, 38, 'limited', 'https://images.unsplash.com/photo-1616671276441-2f2c277b8bf6?w=600&q=80', '{"general":{"ar":"يخفف حرقة المعدة والارتجاع المريئي.","fr":"Soulage les brûlures d''estomac et le reflux.","en":"Relieves heartburn and acid reflux."},"usage":{"ar":"حرقة المعدة بعد الأكل.","fr":"Brûlures après les repas.","en":"Heartburn after meals."},"howToUse":{"ar":"كيس أو ملعقتان بعد الأكل وقبل النوم.","fr":"Un sachet ou deux cuillères après repas et au coucher.","en":"One sachet or two spoons after meals and at bedtime."},"warnings":{"ar":"يحتوي على نسبة من الصوديوم.","fr":"Contient du sodium.","en":"Contains sodium."},"contraindications":{"ar":"حساسية لأحد المكونات.","fr":"Allergie à l''un des composants.","en":"Allergy to any component."},"sideEffects":{"ar":"نادرة جدًا.","fr":"Très rares.","en":"Very rare."}}'::jsonb),
  ('Ventoline', 'cat-respiratory', '{"ar":"سالبوتامول","fr":"Salbutamol","en":"Salbutamol"}'::jsonb, '100mcg', '{"ar":"بخاخ استنشاق","fr":"Inhalateur","en":"Inhaler"}'::jsonb, 42, 'available', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', '{"general":{"ar":"موسع قصبي سريع المفعول يُستخدم في نوبات الربو.","fr":"Bronchodilatateur d''action rapide utilisé lors des crises d''asthme.","en":"A fast-acting bronchodilator used during asthma attacks."},"usage":{"ar":"ضيق التنفس، أزمات الربو.","fr":"Essoufflement, crises d''asthme.","en":"Shortness of breath, asthma attacks."},"howToUse":{"ar":"بخة إلى بختين حسب الحاجة وبإشراف طبي.","fr":"1 à 2 bouffées selon besoin et avis médical.","en":"1–2 puffs as needed under medical guidance."},"warnings":{"ar":"الإفراط في الاستخدام يستوجب مراجعة الطبيب.","fr":"Une utilisation excessive nécessite une consultation médicale.","en":"Overuse requires medical consultation."},"contraindications":{"ar":"اضطرابات قلبية شديدة غير مستقرة.","fr":"Troubles cardiaques sévères non stabilisés.","en":"Severe unstable heart conditions."},"sideEffects":{"ar":"تسارع ضربات القلب، رعشة خفيفة.","fr":"Tachycardie, léger tremblement.","en":"Rapid heartbeat, mild tremor."}}'::jsonb),
  ('Sirop toux Hedex', 'cat-respiratory', '{"ar":"ديكستروميتورفان","fr":"Dextrométhorphane","en":"Dextromethorphan"}'::jsonb, '15mg/5ml', '{"ar":"شراب","fr":"Sirop","en":"Syrup"}'::jsonb, 32, 'out', 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&q=80', '{"general":{"ar":"يستخدم لتهدئة السعال الجاف.","fr":"Utilisé pour calmer la toux sèche.","en":"Used to soothe dry cough."},"usage":{"ar":"السعال الجاف المزعج.","fr":"Toux sèche gênante.","en":"Bothersome dry cough."},"howToUse":{"ar":"ملعقة صغيرة 3 مرات يوميًا حسب العمر.","fr":"Une cuillère à café 3 fois par jour selon l''âge.","en":"One teaspoon 3 times daily depending on age."},"warnings":{"ar":"تجنب القيادة عند الشعور بالنعاس.","fr":"Éviter de conduire en cas de somnolence.","en":"Avoid driving if drowsy."},"contraindications":{"ar":"السعال المصحوب ببلغم غزير.","fr":"Toux grasse avec expectorations abondantes.","en":"Productive cough with heavy phlegm."},"sideEffects":{"ar":"نعاس خفيف، جفاف الفم.","fr":"Somnolence légère, bouche sèche.","en":"Mild drowsiness, dry mouth."}}'::jsonb),
  ('Doliprane Enfant', 'cat-pain', '{"ar":"باراسيتامول","fr":"Paracétamol","en":"Paracetamol"}'::jsonb, '2.4%', '{"ar":"شراب","fr":"Sirop","en":"Syrup"}'::jsonb, 24, 'available', 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80', '{"general":{"ar":"صيغة مخصصة للأطفال لتخفيف الحمى والألم.","fr":"Formule pédiatrique pour soulager fièvre et douleur.","en":"A pediatric formula to relieve fever and pain."},"usage":{"ar":"حمى الأطفال، آلام التسنين.","fr":"Fièvre infantile, douleurs dentaires.","en":"Children''s fever, teething pain."},"howToUse":{"ar":"حسب وزن الطفل، وفق الجرعة المذكورة على العلبة.","fr":"Selon le poids de l''enfant, dose indiquée sur la boîte.","en":"Based on the child''s weight, per the dosing chart on the box."},"warnings":{"ar":"استخدم الحقنة القياسية المرفقة فقط.","fr":"Utiliser uniquement la seringue doseuse fournie.","en":"Use only the provided dosing syringe."},"contraindications":{"ar":"حديثو الولادة دون استشارة طبية.","fr":"Nouveau-nés sans avis médical.","en":"Newborns without medical advice."},"sideEffects":{"ar":"نادرة عند احترام الجرعة.","fr":"Rares en respectant la dose.","en":"Rare when dosage is respected."}}'::jsonb),
  ('Efferalgan Codéine', 'cat-pain', '{"ar":"باراسيتامول + كودايين","fr":"Paracétamol + Codéine","en":"Paracetamol + Codeine"}'::jsonb, '500mg/30mg', '{"ar":"قرص","fr":"Comprimé","en":"Tablet"}'::jsonb, 40, 'limited', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', '{"general":{"ar":"مسكن أقوى يوصف للآلام المتوسطة إلى الشديدة.","fr":"Antalgique renforcé prescrit pour douleurs modérées à sévères.","en":"A stronger pain reliever prescribed for moderate to severe pain."},"usage":{"ar":"آلام ما بعد الجراحة، آلام شديدة.","fr":"Douleurs post-opératoires, douleurs intenses.","en":"Post-surgical pain, intense pain."},"howToUse":{"ar":"يُصرف بوصفة طبية فقط.","fr":"Délivré uniquement sur ordonnance.","en":"Dispensed by prescription only."},"warnings":{"ar":"قد يسبب النعاس، تجنب القيادة.","fr":"Peut provoquer somnolence, éviter de conduire.","en":"May cause drowsiness, avoid driving."},"contraindications":{"ar":"قصور تنفسي حاد.","fr":"Insuffisance respiratoire sévère.","en":"Severe respiratory failure."},"sideEffects":{"ar":"إمساك، دوخة، غثيان.","fr":"Constipation, vertiges, nausées.","en":"Constipation, dizziness, nausea."}}'::jsonb),
  ('Biogaia', 'cat-digestive', '{"ar":"بروبيوتيك","fr":"Probiotique","en":"Probiotic"}'::jsonb, '5ml', '{"ar":"قطرات","fr":"Gouttes","en":"Drops"}'::jsonb, 95, 'available', 'https://images.unsplash.com/photo-1616671276441-2f2c277b8bf6?w=600&q=80', '{"general":{"ar":"مكمل بروبيوتيك يدعم توازن الفلورا المعوية.","fr":"Complément probiotique qui soutient la flore intestinale.","en":"A probiotic supplement that supports gut flora balance."},"usage":{"ar":"اضطرابات هضمية خفيفة، القولون العصبي.","fr":"Troubles digestifs légers, syndrome du côlon irritable.","en":"Mild digestive discomfort, irritable bowel syndrome."},"howToUse":{"ar":"5 قطرات يوميًا مع الطعام.","fr":"5 gouttes par jour avec les repas.","en":"5 drops daily with food."},"warnings":{"ar":"يُحفظ في الثلاجة بعد الفتح.","fr":"Conserver au réfrigérateur après ouverture.","en":"Refrigerate after opening."},"contraindications":{"ar":"لا يوجد موانع رئيسية معروفة.","fr":"Aucune contre-indication majeure connue.","en":"No major known contraindications."},"sideEffects":{"ar":"نادرة جدًا.","fr":"Très rares.","en":"Very rare."}}'::jsonb),
  ('Zinc + Magnésium', 'cat-vitamin', '{"ar":"زنك ومغنيزيوم","fr":"Zinc et magnésium","en":"Zinc and magnesium"}'::jsonb, '15mg/300mg', '{"ar":"كبسولة","fr":"Gélule","en":"Capsule"}'::jsonb, 68, 'available', 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&q=80', '{"general":{"ar":"مكمل غذائي يدعم الطاقة ووظائف العضلات.","fr":"Complément alimentaire qui soutient l''énergie et les fonctions musculaires.","en":"A dietary supplement supporting energy and muscle function."},"usage":{"ar":"التعب العام، تقلصات العضلات.","fr":"Fatigue générale, crampes musculaires.","en":"General fatigue, muscle cramps."},"howToUse":{"ar":"كبسولة واحدة يوميًا مع الطعام.","fr":"Une gélule par jour avec un repas.","en":"One capsule daily with a meal."},"warnings":{"ar":"استشر الصيدلي إذا كنت تتناول علاجات أخرى.","fr":"Demandez conseil si vous suivez un autre traitement.","en":"Consult if you are on other treatments."},"contraindications":{"ar":"قصور كلوي شديد.","fr":"Insuffisance rénale sévère.","en":"Severe renal impairment."},"sideEffects":{"ar":"اضطرابات هضمية خفيفة محتملة.","fr":"Troubles digestifs légers possibles.","en":"Possible mild digestive upset."}}'::jsonb);

insert into public.services (icon, active, name, "shortDesc", details) values
  ('🩸', true, '{"ar":"قياس ضغط الدم","fr":"Mesure de la tension artérielle","en":"Blood pressure check"}'::jsonb, '{"ar":"قياس سريع ودقيق لضغط الدم من طرف فريقنا.","fr":"Mesure rapide et précise de votre tension artérielle.","en":"Fast and accurate blood pressure measurement."}'::jsonb, '{"ar":"خدمة مجانية متوفرة يوميًا داخل الصيدلية، تساعدكم على متابعة صحة القلب والأوعية الدموية بانتظام.","fr":"Service gratuit disponible chaque jour en pharmacie, pour un suivi régulier de votre santé cardiovasculaire.","en":"A free service available daily in-store to help you monitor your cardiovascular health regularly."}'::jsonb),
  ('🍬', true, '{"ar":"قياس نسبة السكر","fr":"Test de glycémie","en":"Blood sugar test"}'::jsonb, '{"ar":"تحقق من مستوى السكر في الدم بسرعة.","fr":"Vérifiez rapidement votre taux de glycémie.","en":"Quickly check your blood sugar level."}'::jsonb, '{"ar":"قياس بسيط باستخدام قطرة دم من الإصبع، مفيد لمتابعة الأشخاص المعرضين لمرض السكري.","fr":"Test simple par goutte de sang au doigt, utile pour le suivi des personnes à risque de diabète.","en":"A simple finger-prick test, useful for monitoring people at risk of diabetes."}'::jsonb),
  ('⚖️', true, '{"ar":"قياس الوزن","fr":"Pesée","en":"Weight measurement"}'::jsonb, '{"ar":"تتبع وزنك بانتظام مجانًا.","fr":"Suivez votre poids régulièrement gratuitement.","en":"Track your weight regularly for free."}'::jsonb, '{"ar":"ميزان طبي دقيق متوفر داخل الصيدلية لمتابعة تطور الوزن.","fr":"Balance médicale précise disponible en pharmacie pour suivre votre poids.","en":"An accurate medical scale available in-store to track weight over time."}'::jsonb),
  ('📏', true, '{"ar":"حساب مؤشر كتلة الجسم","fr":"Calcul de l''IMC","en":"BMI calculation"}'::jsonb, '{"ar":"معرفة مؤشر كتلة جسمك بسهولة.","fr":"Connaître facilement votre IMC.","en":"Easily learn your body mass index."}'::jsonb, '{"ar":"يقوم فريقنا بحساب مؤشر كتلة الجسم وتقديم نصائح عامة حول الوزن الصحي.","fr":"Notre équipe calcule votre IMC et vous donne des conseils généraux sur un poids sain.","en":"Our team calculates your BMI and gives general advice on a healthy weight."}'::jsonb),
  ('💬', true, '{"ar":"الاستشارة الصيدلانية","fr":"Conseil pharmaceutique","en":"Pharmacy consultation"}'::jsonb, '{"ar":"استشر صيدلينا حول أدويتك واستخدامها الآمن.","fr":"Conseils sur vos médicaments et leur usage sécurisé.","en":"Advice on your medicines and their safe use."}'::jsonb, '{"ar":"فريقنا الصيدلاني متاح للإجابة عن أسئلتكم حول التداخلات الدوائية والاستخدام الصحيح.","fr":"Notre équipe est disponible pour répondre à vos questions sur les interactions et le bon usage des médicaments.","en":"Our pharmacy team is available to answer your questions about drug interactions and proper use."}'::jsonb),
  ('🧴', true, '{"ar":"استشارة العناية بالبشرة","fr":"Conseil dermo-cosmétique","en":"Skincare consultation"}'::jsonb, '{"ar":"نصائح مخصصة لمنتجات العناية بالبشرة.","fr":"Conseils personnalisés en produits de soin.","en":"Personalized advice on skincare products."}'::jsonb, '{"ar":"مساعدتكم في اختيار المنتجات المناسبة لنوع بشرتكم واحتياجاتكم.","fr":"Nous vous aidons à choisir les produits adaptés à votre type de peau.","en":"We help you choose the right products for your skin type and needs."}'::jsonb);

insert into public.staff (name, role, bio, image) values
  ('Ahmed Bennani', '{"ar":"صيدلي مسؤول","fr":"Pharmacien titulaire","en":"Lead Pharmacist"}'::jsonb, '{"ar":"متخصص في الإرشاد الدوائي وخدمة الزبناء بخبرة تفوق 10 سنوات.","fr":"Spécialisé en conseil pharmaceutique avec plus de 10 ans d''expérience.","en":"Specialized in pharmaceutical guidance with over 10 years of experience."}'::jsonb, 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&q=80'),
  ('Fatima Zahra Idrissi', '{"ar":"صيدلانية","fr":"Pharmacienne","en":"Pharmacist"}'::jsonb, '{"ar":"خبيرة في مجال التغذية العلاجية ومتابعة الأمراض المزمنة.","fr":"Experte en nutrition thérapeutique et suivi des maladies chroniques.","en":"Expert in therapeutic nutrition and chronic disease follow-up."}'::jsonb, 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&q=80'),
  ('Youssef El Amrani', '{"ar":"مساعد صيدلي","fr":"Assistant pharmacien","en":"Pharmacy Assistant"}'::jsonb, '{"ar":"يساعد الزبائن في إيجاد المنتجات المناسبة بسرعة وابتسامة.","fr":"Aide les clients à trouver rapidement les bons produits, avec le sourire.","en":"Helps customers find the right products quickly, with a smile."}'::jsonb, 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80'),
  ('Salma Ouazzani', '{"ar":"مستشارة تجميل","fr":"Conseillère beauté","en":"Beauty Advisor"}'::jsonb, '{"ar":"متخصصة في منتجات العناية بالبشرة والتجميل الصيدلاني.","fr":"Spécialisée en produits de soin et cosmétique pharmaceutique.","en":"Specialized in skincare and pharmaceutical cosmetics."}'::jsonb, 'https://images.unsplash.com/photo-1607990283143-e81e7a2c9349?w=400&q=80'),
  ('Karim Tazi', '{"ar":"صيدلي مناوب","fr":"Pharmacien de garde","en":"On-duty Pharmacist"}'::jsonb, '{"ar":"يضمن استمرارية الخدمة خلال المناوبات المسائية وأيام العطل.","fr":"Assure la continuité du service durant les gardes du soir et les jours fériés.","en":"Ensures service continuity during evening shifts and holidays."}'::jsonb, 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&q=80');

insert into public.announcements (active, icon, text) values
  (true, '📢', '{"ar":"خدمة قياس ضغط الدم متوفرة لدينا مجانًا","fr":"Service de mesure de la tension artérielle disponible gratuitement","en":"Free blood pressure check available now"}'::jsonb),
  (true, '🕐', '{"ar":"صيدليتنا مفتوحة اليوم حتى الساعة 22:00","fr":"Notre pharmacie est ouverte aujourd''hui jusqu''à 22h00","en":"Our pharmacy is open today until 10:00 PM"}'::jsonb),
  (true, '💊', '{"ar":"استفسر عن توفر دوائك قبل زيارتنا","fr":"Vérifiez la disponibilité de votre médicament avant de venir","en":"Check your medicine availability before visiting us"}'::jsonb),
  (true, '🎉', '{"ar":"تخفيضات على منتجات العناية بالبشرة هذا الأسبوع","fr":"Réductions sur les produits de soin cette semaine","en":"Discounts on skincare products this week"}'::jsonb);

insert into public.health_guides ("categoryId", active, title, cover, intro, "keyPoints", tips) values
  ('gc-diabetes', true, '{"ar":"أساسيات التغذية لمرضى السكري","fr":"Bases de la nutrition pour les diabétiques","en":"Nutrition basics for diabetics"}'::jsonb, 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80', '{"ar":"التغذية السليمة عنصر أساسي في ضبط مستوى السكر في الدم والحفاظ على الطاقة طوال اليوم.","fr":"Une alimentation adaptée est essentielle pour contrôler la glycémie et maintenir votre énergie.","en":"Proper nutrition is essential for controlling blood sugar and maintaining energy throughout the day."}'::jsonb, '{"ar":["اختر الكربوهيدرات المعقدة بدل البسيطة","وزّع وجباتك على مدار اليوم","راقب كمية السكريات المضافة"],"fr":["Préférez les glucides complexes","Répartissez vos repas dans la journée","Surveillez les sucres ajoutés"],"en":["Choose complex carbs over simple ones","Spread meals throughout the day","Watch added sugar intake"]}'::jsonb, '{"ar":["ابدأ وجباتك بالخضروات","تجنب المشروبات الغازية السكرية","مارس نشاطًا بدنيًا خفيفًا بعد الأكل"],"fr":["Commencez vos repas par des légumes","Évitez les sodas sucrés","Marchez un peu après les repas"],"en":["Start meals with vegetables","Avoid sugary sodas","Take a short walk after meals"]}'::jsonb),
  ('gc-diabetes', true, '{"ar":"قراءة الملصقات الغذائية لمرضى السكري","fr":"Lire les étiquettes alimentaires","en":"Reading food labels for diabetics"}'::jsonb, 'https://images.unsplash.com/photo-1580983230786-315dfb9c8c31?w=800&q=80', '{"ar":"معرفة كيفية قراءة الملصقات الغذائية يساعدك على اختيار المنتجات الأنسب.","fr":"Savoir lire les étiquettes vous aide à choisir les produits les plus adaptés.","en":"Knowing how to read food labels helps you choose the most suitable products."}'::jsonb, '{"ar":["انتبه لكمية السكريات لكل 100 غرام","تحقق من الألياف الغذائية","راقب حجم الحصة الموصى بها"],"fr":["Vérifiez les sucres pour 100g","Regardez les fibres alimentaires","Notez la portion recommandée"],"en":["Check sugars per 100g","Look at dietary fiber","Note the recommended serving size"]}'::jsonb, '{"ar":["قارن بين منتجات مشابهة قبل الشراء","ابحث عن عبارة \"بدون سكر مضاف\""],"fr":["Comparez des produits similaires avant d''acheter","Recherchez la mention \"sans sucre ajouté\""],"en":["Compare similar products before buying","Look for \"no added sugar\" labels"]}'::jsonb),
  ('gc-hypertension', true, '{"ar":"تقليل الملح في نظامك الغذائي","fr":"Réduire le sel dans votre alimentation","en":"Reducing salt in your diet"}'::jsonb, 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80', '{"ar":"تقليل استهلاك الملح يساهم بشكل مباشر في ضبط ضغط الدم.","fr":"Réduire le sel contribue directement à contrôler votre tension artérielle.","en":"Reducing salt intake directly helps control blood pressure."}'::jsonb, '{"ar":["تجنب الأطعمة المصنعة الغنية بالملح","استبدل الملح بالأعشاب والتوابل","اقرأ نسبة الصوديوم على الملصقات"],"fr":["Évitez les aliments transformés riches en sel","Remplacez le sel par des herbes","Lisez la teneur en sodium"],"en":["Avoid processed foods high in salt","Replace salt with herbs and spices","Read sodium content on labels"]}'::jsonb, '{"ar":["قلّل الملح تدريجيًا لتعتاد ذائقتك","تجنب المخللات والمقبلات الجاهزة"],"fr":["Réduisez le sel progressivement","Évitez les conserves et apéritifs salés"],"en":["Reduce salt gradually to adjust your taste","Avoid pickles and ready-made salty snacks"]}'::jsonb),
  ('gc-hypertension', true, '{"ar":"النشاط البدني وضغط الدم","fr":"Activité physique et tension artérielle","en":"Physical activity and blood pressure"}'::jsonb, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80', '{"ar":"ممارسة الرياضة بانتظام تساعد على خفض ضغط الدم بشكل طبيعي.","fr":"L''exercice régulier aide à réduire naturellement la tension artérielle.","en":"Regular exercise naturally helps lower blood pressure."}'::jsonb, '{"ar":["30 دقيقة مشي يوميًا كافية للبدء","اختر نشاطًا تستمتع به لتستمر عليه","استشر طبيبك قبل بدء نشاط مكثف"],"fr":["30 minutes de marche par jour suffisent","Choisissez une activité que vous aimez","Consultez avant une activité intense"],"en":["30 minutes of walking daily is a good start","Choose an activity you enjoy","Consult before intense activity"]}'::jsonb, '{"ar":["ابدأ بخطوات صغيرة وزد تدريجيًا","مارس النشاط في نفس الوقت يوميًا لتكوين عادة"],"fr":["Commencez petit et augmentez progressivement","Pratiquez à heure fixe pour créer une habitude"],"en":["Start small and increase gradually","Exercise at the same time daily to build a habit"]}'::jsonb),
  ('gc-cholesterol', true, '{"ar":"الدهون المشبعة وتأثيرها","fr":"Les graisses saturées et leur impact","en":"Saturated fats and their impact"}'::jsonb, 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80', '{"ar":"تقليل الدهون المشبعة يساعد في الحفاظ على مستوى كوليسترول صحي.","fr":"Réduire les graisses saturées aide à maintenir un taux de cholestérol sain.","en":"Reducing saturated fats helps maintain a healthy cholesterol level."}'::jsonb, '{"ar":["قلّل اللحوم الدهنية والزبدة","اختر منتجات ألبان قليلة الدسم","استبدل القلي بالشوي أو الطهي بالبخار"],"fr":["Réduisez viandes grasses et beurre","Choisissez des laitages allégés","Préférez grillé ou vapeur à la friture"],"en":["Reduce fatty meats and butter","Choose low-fat dairy products","Prefer grilling or steaming over frying"]}'::jsonb, '{"ar":["أضف الأفوكادو وزيت الزيتون كدهون صحية","اقرأ نسبة الدهون المشبعة على الملصقات"],"fr":["Ajoutez avocat et huile d''olive","Lisez la teneur en graisses saturées"],"en":["Add avocado and olive oil as healthy fats","Read saturated fat content on labels"]}'::jsonb),
  ('gc-cholesterol', true, '{"ar":"دور الألياف في خفض الكوليسترول","fr":"Le rôle des fibres","en":"The role of fiber"}'::jsonb, 'https://images.unsplash.com/photo-1580983230786-315dfb9c8c31?w=800&q=80', '{"ar":"الألياف الغذائية تساهم في خفض الكوليسترول الضار بشكل طبيعي.","fr":"Les fibres alimentaires aident à réduire naturellement le mauvais cholestérol.","en":"Dietary fiber naturally helps reduce bad cholesterol."}'::jsonb, '{"ar":["تناول الشوفان والبقوليات بانتظام","أكثر من الخضروات والفواكه الطازجة","اختر الخبز والحبوب الكاملة"],"fr":["Consommez avoine et légumineuses","Mangez plus de fruits et légumes frais","Choisissez pain et céréales complètes"],"en":["Eat oats and legumes regularly","Eat more fresh fruits and vegetables","Choose whole grain bread and cereals"]}'::jsonb, '{"ar":["ابدأ يومك بوجبة شوفان","أضف بذور الشيا أو الكتان لوجباتك"],"fr":["Commencez la journée avec de l''avoine","Ajoutez des graines de chia ou de lin"],"en":["Start your day with an oat meal","Add chia or flax seeds to your meals"]}'::jsonb),
  ('gc-weight', true, '{"ar":"تنظيم أحجام الحصص الغذائية","fr":"Gérer la taille des portions","en":"Managing portion sizes"}'::jsonb, 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80', '{"ar":"التحكم في حجم الحصص يساعد على إدارة الوزن دون الحاجة لحرمان شديد.","fr":"Contrôler les portions aide à gérer le poids sans privation excessive.","en":"Controlling portion sizes helps manage weight without excessive restriction."}'::jsonb, '{"ar":["استخدم أطباقًا أصغر حجمًا","تناول الطعام ببطء وانتبه لإشارات الشبع","تجنب الأكل أمام الشاشات"],"fr":["Utilisez des assiettes plus petites","Mangez lentement en écoutant votre satiété","Évitez de manger devant un écran"],"en":["Use smaller plates","Eat slowly and notice fullness cues","Avoid eating in front of screens"]}'::jsonb, '{"ar":["اشرب كوب ماء قبل الوجبة","خطط لوجباتك مسبقًا لتفادي الأكل العشوائي"],"fr":["Buvez un verre d''eau avant le repas","Planifiez vos repas à l''avance"],"en":["Drink a glass of water before meals","Plan your meals ahead to avoid random snacking"]}'::jsonb),
  ('gc-weight', true, '{"ar":"المشروبات وتأثيرها على الوزن","fr":"Les boissons et leur impact sur le poids","en":"Drinks and their impact on weight"}'::jsonb, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80', '{"ar":"السعرات الحرارية الخفية في المشروبات كثيرًا ما تُهمَل رغم تأثيرها الكبير.","fr":"Les calories cachées dans les boissons sont souvent négligées.","en":"Hidden calories in drinks are often overlooked despite their impact."}'::jsonb, '{"ar":["استبدل المشروبات الغازية بالماء","قلّل السكر في القهوة والشاي","انتبه لسعرات العصائر الصناعية"],"fr":["Remplacez les sodas par de l''eau","Réduisez le sucre dans le café et thé","Attention aux jus industriels"],"en":["Replace sodas with water","Reduce sugar in coffee and tea","Watch calories in industrial juices"]}'::jsonb, '{"ar":["أضف شرائح ليمون أو نعناع للماء لتنويع الطعم","احمل زجاجة ماء معك خلال اليوم"],"fr":["Ajoutez citron ou menthe à votre eau","Gardez une bouteille d''eau sur vous"],"en":["Add lemon or mint slices to your water","Carry a water bottle with you during the day"]}'::jsonb);

insert into public.pharmacy_info (id, name, slogan, description, address, city, phone, whatsapp, email, "mapUrl", "mapLink", "logoInitial", "openingHours", images, socials) values
  (1, '{"ar":"صيدلية النور","fr":"Pharmacie Al Nour","en":"Al Nour Pharmacy"}'::jsonb, '{"ar":"رعايتك الصحية تبدأ من هنا","fr":"Votre santé commence ici","en":"Your healthcare starts here"}'::jsonb, '{"ar":"صيدلية النور صيدلية عصرية تقدم خدماتها لزبائنها منذ أكثر من 12 سنة، بفريق صيدلاني متخصص ومجموعة واسعة من الأدوية والخدمات الصحية.","fr":"Pharmacie Al Nour est une pharmacie moderne au service de ses clients depuis plus de 12 ans, avec une équipe pharmaceutique spécialisée et une large gamme de médicaments et services de santé.","en":"Al Nour Pharmacy is a modern pharmacy serving its customers for over 12 years, with a specialized pharmacy team and a wide range of medicines and health services."}'::jsonb, '{"ar":"شارع الحسن الثاني، رقم 24","fr":"Avenue Hassan II, N°24","en":"Hassan II Avenue, No. 24"}'::jsonb, '{"ar":"مكناس","fr":"Meknès","en":"Meknes"}'::jsonb, '+212 5 35 12 34 56', '+212 6 61 23 45 67', 'contact@alnour-pharmacy.ma', 'https://www.google.com/maps?q=Meknes,Morocco&output=embed', 'https://www.google.com/maps?q=Meknes,Morocco', 'ن', '{"mon":{"open":"08:30","close":"22:00","closed":false},"tue":{"open":"08:30","close":"22:00","closed":false},"wed":{"open":"08:30","close":"22:00","closed":false},"thu":{"open":"08:30","close":"22:00","closed":false},"fri":{"open":"08:30","close":"22:00","closed":false},"sat":{"open":"09:00","close":"20:00","closed":false},"sun":{"open":"09:00","close":"13:00","closed":false}}'::jsonb, '["https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=1200&q=80","https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=1200&q=80","https://images.unsplash.com/photo-1622902046580-2b47f47f5471?w=1200&q=80"]'::jsonb, '{"facebook":"https://facebook.com","instagram":"https://instagram.com"}'::jsonb)
on conflict (id) do update set
  name = excluded.name, slogan = excluded.slogan, description = excluded.description,
  address = excluded.address, city = excluded.city, phone = excluded.phone,
  whatsapp = excluded.whatsapp, email = excluded.email, "mapUrl" = excluded."mapUrl",
  "mapLink" = excluded."mapLink", "logoInitial" = excluded."logoInitial",
  "openingHours" = excluded."openingHours", images = excluded.images, socials = excluded.socials;
